sources:
  - name: ens
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/ensdomains/ens
  - name: uniswapv2
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2

plugins:
  - pollingLive:
      defaultInterval: 5000

documents:
  - src/graphql/*.graphql
