sources:
  - name: ens
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/ensdomains/ens
  - name: usdc
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/centrehq/usdc

documents:
  - src/graphql/*.graphql
